version: '3'
services:
  embeddings:
    container_name: embeddings
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL=${MODEL:-all-MiniLM-L6-v2}
      - PORT=${PORT:-5000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:${PORT}/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
